# -*- coding: utf-8 -*-
"""
Created on Sat Feb 11 16:24:07 2017

@author: raphaelle
"""



import nltk
from bs4 import BeautifulSoup
import urllib
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
import json

def list_duplicates_of(seq,item):
    start_at = -1
    locs = []
    while True:
        try:
            loc = seq.index(item,start_at+1)
        except ValueError:
            break
        else:
            locs.append(loc)
            start_at = loc
    return locs

url = 'http://renaissanceastrology.com/agrippamoon.html'
html = urllib.urlopen(url)
raw = BeautifulSoup(html).get_text()
raw= u"\n\n\n\n\nCornelius Agrippa on the Things Ruled by the Moon\n\n\n\n\n\n\n\n\nSERVICES\n\n\nPAYMENT\n\n\nCOURSES\n\n\nBOOKS\n\n\nCONTACT\n\n\nSEARCH\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nChristopher Warnock, Esq.\n\n\n\n\n Agrippa on the Lunar Things\r\n\r\n\n\n\n\n\nHOME\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCornelius Agrippa on Saturn \n\n\n\n\nCornelius Agrippa on Jupiter \n\n\n\n\nCornelius Agrippa on Mars \n\n\n\n\nCornelius Agrippa on the Sun \n\n\n\n\nCornelius Agrippa on Venus \n\n\n\n\nCornelius Agrippa on Mercury \n\n\n\n\nCornelius Agrippa on the Moon \n\n\n\n\n\n\n\n\nLilly on Saturn \n\n\n\n\nLilly on  Jupiter \n\n\n\n\nLilly on  Mars \n\n\n\n\nLilly on the Sun \n\n\n\n\nLilly on  Venus \n\n\n\n\nLilly on  Mercury \n\n\n\n\nLilly on the Moon \n\n\n  Web Site Search\n\n\n\n\n\n\n\n\nWhat things are Lunar or\r\nunder the power of the Moon\r\n\n\n\r\nfrom Cornelius Agrippa's Three Books of Occult Philosophy\n\n\n\nElements & Tastes\nMetals & Stones\nPlants & Trees\nFoods\nAnimals\nBirds\nFish\nRegions & Countries\nIncense\nPlaces\n\n\n\n\n\n\n\n\nBOOK ONE\n\n\n\r\nCHAPTER XXIV.\r\n\n What things are Lunary or under the power of the Moon.\n\n\n\n\n\nThese things are Lunary, \r\namongst Elements,  the Earth, \r\nthen the Water, as well that of the Sea, as of the Rivers, and \r\nall moist things, as the moisture of Trees, and Animals, especially \r\nthey which are White, as the Whites of Eggs, fat, sweat, flegme, and \r\nthe superfluities of bodies. Amongst tasts, salt, and insipid.\r\n\r\n\nAmongst  Metals, Silver. \r\namongst stones, Crystall, the Silver Marcasite, and all those stones \r\nthat are White, and Green. Also the stone Selenites, Lunary, shining from \r\na white body, with a yellow brightness, imitating the motion of the Moon, \r\nhaving in it the figure of the Moon which daily increaseth, or decreaseth \r\nas doth the Moon. Also Pearls, which are generated in shels of fishes from\r\n the droppings of Water, also the Berill. \r\n\r\n\nAmongst\r\n  Plants and Trees,\r\n\r\n these are Lunary, as the Selenotropion, which turns towards the Moon, \r\nas doth the Heliotropion towards the Sun, and the Palme tree sends forth\r\n a bough at every rising of the Moon. Hyssope also, and Rosemary, Agnus\r\n Castu, and the Olive-tree, are Lunary. Also the Hearb Chinosta,\r\n which increaseth, and decreaseth with the Moon,  in substance, \r\nand number of leaves, not only in Sap, and vertue, which indeed\r\n is in some sort common to all Plants, except Onions, which are \r\nunder the influence of Mars, which have contrary properties.\r\n\r\n\r\n\r\n\namongst  Animals \r\n\r\nare such as delight to be in mans company, and such as do naturally excell \r\nin love, or hatred, as all kinds of Dogs. The Chameleon also is Lunary, \r\nwhich alwaies assumes a colour according to the variety of the colour \r\nof the object. as the Moon changeth her nature according to the variety\r\n of the Signe which it is found in. \r\n\nLunary also are Swine, Hinds, Goats,\r\n and all Animals whatsoever, that observe, and imitate the motion of the \r\nMoon. As the Baboon, and Panther, which is said to have a spot upon her \r\nshoulder like the Moon, increasing into a roundness, and having horns that\r\n bend inwards. Cats also are Lunary, whose eyes become greater or less, \r\naccording to the course of the Moon. and those things which are of like\r\n nature, as Menstruous blood, of which are made wonderfull and strange \r\nthings by Magicians. \r\n\nLhe Civet-Cat also changing her sex, being obnoxious \r\nto divers Sorceries, and all Animals that live in water as well as on land.\r\n as Otters, and such as prey upon fish. Also all Monstrous beasts, such as\r\n without any manifest seed are equivocally generated, as Mice, \r\nwhich sometimes are generated by Coition, sometimes of the putrefaction of the Earth. \r\n\r\n\r\n\r\n\nAmongst birds, \r\n Geese, Ducks, Didoppers, and all kind of watery fowl\r\n as prey upon fish, as the Heron, and those that are equivocally produced,\r\n as Wasps of the Carkases of horses. Bees of the putrefaction of Cows,\r\n small Flies of putrefied wine, and Betles of the flesh of Asses.\r\n \r\n\nBut most Lunary of all is the two-horned \r\nBetle, horned after the manner of a\r\n Bull. which digs under Cow-dung, and there remaines for the space of \r\ntwenty eight daies, in which time the Moon measures the whole Zodiack, \r\nand in the twenty ninth day, when it thinks there will be a conjunction\r\n of their brightness, it opens the dung and casts it into Water, from\r\n whence then come Betles.\r\n\r\n\nAmongst fish, \r\nthese are Lunary, Aelurus, whose eyes are changed according to the\r\n course of the Moon, and whatsoever observes the motion of the Moon, \r\nas the Tortoise, the Echeneis, Crabs, Oisters, Cockles, and Frogs. \r\n\r\n\r\n\r\n\n\n\n\n\r\nCHAPTER XXXI.\r\n\nHow Provinces, and Kingdoms are Distributed to Planets.\n\n\n\n\nTOP\nThe Moon with Cancer governs Bithivia, Phrygia, Colchica,\r\nNumidia, Africa, Carthage and all Carchedonia. \r\n\r\n\r\n\n\n\n\n\r\nCHAPTER XLIV.\r\n\nThe Composition of Some Fumes Appropriated to the Planets.\n\n\n\n\n\nFor the Moon we make a suffimigation of the head of\r\na frog dried, the eyes of a bull, the seed of a white poppy, frankincense and camphor,\r\nwhich must be incorporated with menstruous blood or the blood of a goose.\r\n\r\n\nTo the Moon the leaves of all vegetables, as the leaf\r\nIndum, the leaves of the myrtle and the bay tree. \r\n\n\n\n\n\r\nCHAPTER XLVII.\r\n\nWhat Places are Suitable to Every Star\n\n\n\n\n\nTo the Moon, wildernesses, woods, rocks, hills,\r\nmountains, forests, fountains, waters, rivers, seas, seashores, ships, groves,\r\nhighways, granaries for corn and such like. \r\n\n\n\n\n\n\nTOP\n\n\n\n\nHOME\n\n\n\r\n\r\nPlease Contact me with any Questions or Comments.\r\n\n\r\nCopyright 2003 Christopher Warnock, All Rights Reserved.\r\n\r\n\r\n\r\n\n\n"

sentences = sent_tokenize(raw)

keywords_list = ['Amongst', 'amongst', 'XXXI', 'XLIV', 'XLVII']
idx_list = []
for sent in sentences :
    for keyword in keywords_list :
        if keyword in sent :
            idx_list.append(sentences.index(sent))
        
idx_list = sorted(list(set(idx_list)))
start=-1
stop =0
slices= []
for i in range(len(idx_list)) :
    start+=1
    stop+=1
    try :
        slices.append(sentences[idx_list[start]:idx_list[stop]])
    except IndexError,e :
        slices.append(sentences[idx_list[stop-1]:])
tagged = {}
for i in slices :
    token = []
    for sent in i : 
        token.append(nltk.pos_tag((nltk.word_tokenize(sent))))
    tagged[slices.index(i)]=token

tagged[10] = tagged[10][:-2]

moon = {}
for k, v in tagged.iteritems() :
    moon[k] = {}
    for sent in v :
        for word in sent :
            
            if word[0] == "Amongst" :
                moon[k][sent[sent.index(word) + 1][0]] = []
                try :
                    sent.remove(word)
                    sent.remove(sent[sent.index(word) + 1])
                except ValueError, e : 
                    pass
            elif word[0] == "amongst" :
                moon[k][sent[sent.index(word) + 1][0]] = []
                try :
                    sent.remove(word)
                    sent.remove(sent[sent.index(word) + 1])
                except ValueError, e:
                    pass
            elif "CHAPTER" in word[0] :
                v.remove(sent)
            elif word[0] == "TOP" :
                try :
                    sent.remove(word)
                except ValueError, e:
                    pass
            elif word[0] == "moon" :
                try :
                    sent.remove(word)
                    sent.remove(sent[sent.index(word) + 1])
                    sent.remove(sent[sent.index(word) - 1])
                except ValueError, e:
                    pass

for sent in tagged[9] :
    for word in sent :
        if "Fumes" in word[0] :
            moon[9]["Fumes"] = []
            tagged[9].remove(sent)
        elif "fumes" in word[0] :
            sent.remove(word)
for sent in tagged[8] :
    for word in sent :
        if "Provinces" in word[0] :
            moon[8]["Provinces"] = []
            tagged[8].remove(sent)
for sent in tagged[10] :
    for word in sent :
        if "Places" in word[0] :
            moon[10]["Places"] = []
cleaned = {}
for k, v in tagged.iteritems() :
    cleaned[k] = []
    for sent in v :
        for word in sent :
            if word[0] not in stopwords.words('english') :
                cleaned[k].append(word[0])
                



for k,v in cleaned.iteritems() :
    idx = list_duplicates_of(cleaned[k], ',')
    stt = -1
    stp=0
    for i in range(len(idx)) :
        stt+=1
        stp+=1
        try :
            moon[k][moon[k].keys()[0]].append(v[idx[stt]:idx[stp]])
        except IndexError,e:
            moon[k][moon[k].keys()[0]].append(v[idx[stp-1]:])


f = open('~/astrologie/moon.json', 'w')
f.write(json.dumps(moon, indent=1))
f.close()


